class kaamelott:
	Livre_1_Tome_1_Episode_01 = '_**Heat**_ \n *Dans un camp à l’intérieur de la forêt.* \n **Karadoc : ** Bon, je vais essayer de trouver un petit lièvre pour ce soir parce qu’il commence à faire faim ! \n **Bohort :** Je me demande comment vous faîtes, moi je serais incapable de trouver de quoi manger dans la forêt. \n **Karadoc :** Pour attraper des bêtes, il faut imiter les femelles. Là, pour le coup, hop ! La femelle lièvre. \n **Bohort :** La hase. \n **Karadoc :** De quoi ? \n **Bohort :** La femelle lièvre, c’est la hase. \n **Karadoc :** Ah non, moi je connais que le cri. \n *Il fait un bruit étrange.* \n *** \n **GENERIQUE** \n ***'

	tabkaamelott = ['**C’est pas faux !**', 
	'**Qu’est-ce qui est petit et marron ? \nUn marron ! \nPutain il est fort, ce con.**',
	'**Hé les connards ! Vous pouvez faire griller un porcelet s’il vous plaît ? \nLes connards ? \nS’il vous plaît ?**',
	'**À l’époque quand je levais le doigt, y’avait 15 000 soldats qui gueulaient IMPERATOR ! Maintenant quand j’lève le doigt c’est pour aller pisser…**',
	'**Nouvelle technique : on passe pour des cons, les autres se marrent, et on frappe. C’est nouveau. \nEt les autres font ça aussi ? \nAh non, ça c’est que nous. Parce qu’il faut être capable de passer pour des cons en un temps record. Ah non, là-dessus on a une avance considérable.**',
	'**- C’est vrai que vous êtes le fils d’un démon et d’une pucelle ? \nOui pourquoi ? \nVous avez plus pris de la pucelle…**',
	'**Moi, je m’en fous, si on me force à y retourner, je retiens ma respiration jusqu’à ce qu’on arrête de me forcer à y retourner.**',
	'**Oh vous, toujours vous, mais allez chier dans une fiole, on verra après.**',
	'**J’irai me coucher quand vous m’aurez juré qu’il n’y a pas dans cette forêt d’animal plus dangereux que le lapin adulte !**',
	'**Vous croyez vraiment que vous avez les moyens de me convoquer ? Je suis là parce j’veux bien et si vous m’avez fait venir pour rien, j’vous balance 15 jours dans une geôle sans boire ni bouffer et j’me démerde pour que vous chopiez le typhus !**',
	'**Je ne mange pas de graines !!**',
	'**Faut pas respirer la compote, ça fait tousser.**',
	'**Le gras c’est la vie !**',
	'**Arthur :** Mais c’est pas compliqué, bon Dieu ! Y a Calogrenant à droite, Léodagan à gauche, et nous on arrive par le milieu ! \n**Lancelot :** C’est bon jusque là ? \n**Perceval :** Attendez, moi, si je me souviens bien du coin, il y a la rivière qui passe en travers ! \n**Arthur :** Ah, mais merde avec votre rivière ! \n**Perceval :** C’est un point de repère comme un autre ! \n**Lancelot :** Mais bon Dieu, il y a pas besoin de point de repère puisque les envahisseurs vont nous attaquer de face ! \n**Perceval :** De face, ça va ! C’est le reste qui va pas ! \n**Arthur :** Mais quoi, nom d’un chien !? \n**Perceval :** Ben la gauche, la droite, là ! Moi j’aime pas ces trucs ! \n**Lancelot :** Mais qu’est ce que vous aimez pas ? \n**Perceval :* Ces conneries de gauche et de droite ! Ça veut rien dire ces machins ! Selon comme on est tourné ça change tout ! \n**Arthur :** Mais qu’est ce que vous nous chantez ? \n**Perceval :** Moi j’estime que quand on parle tactique militaire, il faut employer des termes précis ! \n**Lancelot :** Ben oui, effectivement, ça peut prêter à confusion… \n**Arthur :** Non mais attendez, nous c’est pour vous qu’on dit gauche et droite ! C’est pour pas vous embrouiller ! \n**Perceval :** Si, ça m’embrouille ! \n**Lancelot :** Ah bon ? On peut parler normalement alors ?\n**Perceval :** Professionnel ! \n**Arthur :** Bon, ben alors, OK, on reprend depuis le début ; donc, Calogrenant est posté depuis hier soir au Nord-Est de la zone d’attaque… \n**Lancelot :** … Léodagan, Sud-Sud-Est, un peu plus en retrait avec ses cavaliers… \n**Perceval :** Moi j’aime pas ces histoires de Sud-Est, Nord-Ouest, et tous ces machins ! \n**Arthur :** Quoi, qu’est ce qu’il y a qui va pas encore ?! \n**Perceval :** C’est un coup à se planter ça ! De toutes façons, on dit le Nord ! Selon comme on est tourné ça change tout !',
	'**Et va falloir vous y faire parce qu’à partir de maintenant, on va s’appeler « Les Chevaliers de la Table Ronde » ! \nBen heureusement qu’on s’est pas fait construire un buffet à vaisselle !**',
	'**Vous pouvez être sûr que si Joseph d’Arimathie a pas été trop con, le graal, c’est un bocal à anchois !**',
	'**Vous avez été marié comme moi ; vous savez que la monstruosité peut prendre des formes diverses.**',
	'**J’suis un marteau moi, je crame tout moi, sa ferme, ma ferme, celles des autres, le château, j’fait flamber le moitié de la Bretagne.**',
	'**Elle est où la poulette ?**',
	'**- Dites euh vous auriez pas essayé d’me la faire à la pute par hasard ? \n- C’est à dire ? \n- C’est à dire conduire les vandales par l’ouest pour me prendre en traître pendant que j’suis occupé avec les romains à l’est. \n- Écoutez… Comme ça à priori euh ça m’évoque rien, mais honnêtement c’est possible ! Ce serait assez le genre de la maison en tout cas. De l’autre côté, voyez un peu l’ironie ! Si j’avais pas fomenté une attaque par l’ouest, vous seriez allé vous écraser contre les romains à l’est ! OUI ! Alors pourquoi ?! Pourquoi trahir sans arrêt les gens avec qui je collabore ? Je dirais que c’est probablement une réponse compulsive à une crainte de m’attacher ! Briser une relation plutôt que la cultiver pour ne pas se retrouver démuni face au bonheur ! OUI, pour répondre à votre question : j’ai peur d’aimer. \n- Alors moi euh j’veux bien passer l’éponge euh, sur vos tentatives de putsch euh, vos combines véreuses, vos alliances bidons et tout le reste. En revanche, si vous la fermez pas tout de suite euh définitivement hein ? Je vous aplati les boules avec ça.**',
	'**PAYS DE GALLE INDÉPENDAAAAAAAAAAAAAAAAAAAANT.**',
	'**CUUUUUUUUUILLÈÈÈÈÈÈRE !!**',
	'**Alors le chevalier il crie au romain : « Hey ! Vous vous prenez pour le Colisée ! » \nOh la vache mais c’est nul !**'
	]